import type { Config } from 'tailwindcss';

const config: Config = {
  darkMode: 'class',
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
    './src/features/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        background: '#fbf9f8',
        surface: '#fbf9f8',
        'surface-bright': '#fbf9f8',
        'surface-dim': '#dbd9d9',
        'surface-variant': '#e4e2e2',
        'surface-tint': '#95491f',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f5f3f3',
        'surface-container': '#efeded',
        'surface-container-high': '#eae8e7',
        'surface-container-highest': '#e4e2e2',
        'on-surface': '#1b1c1c',
        'on-surface-variant': '#54433b',
        'on-background': '#1b1c1c',
        'inverse-surface': '#303030',
        'inverse-on-surface': '#f2f0f0',
        outline: '#87736a',
        'outline-variant': '#dac1b7',
        primary: '#95491f',
        'on-primary': '#ffffff',
        'primary-container': '#ff9d6c',
        'on-primary-container': '#773209',
        'primary-fixed': '#ffdbcc',
        'primary-fixed-dim': '#ffb693',
        'on-primary-fixed': '#351000',
        'on-primary-fixed-variant': '#773208',
        'inverse-primary': '#ffb693',
        secondary: '#5550bc',
        'on-secondary': '#ffffff',
        'secondary-container': '#938efe',
        'on-secondary-container': '#281d8e',
        'secondary-fixed': '#e3dfff',
        'secondary-fixed-dim': '#c4c0ff',
        'on-secondary-fixed': '#110069',
        'on-secondary-fixed-variant': '#3d36a2',
        tertiary: '#735c00',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#d5b243',
        'on-tertiary-container': '#574500',
        'tertiary-fixed': '#ffe088',
        'tertiary-fixed-dim': '#e7c353',
        'on-tertiary-fixed': '#241a00',
        'on-tertiary-fixed-variant': '#574500',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
      },
      borderRadius: {
        sm: '0.5rem',
        DEFAULT: '1rem',
        md: '1.5rem',
        lg: '2rem',
        xl: '3rem',
        full: '9999px',
      },
      spacing: {
        unit: '8px',
        gutter: '16px',
        'margin-mobile': '24px',
        'margin-desktop': '64px',
        'section-gap': '48px',
      },
      fontFamily: {
        sans: ['var(--font-nunito)', 'system-ui', 'sans-serif'],
        cursive: ['var(--font-passions)', 'cursive'],
      },
      fontSize: {
        'headline-lg': ['40px', { lineHeight: '48px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg-mobile': ['30px', { lineHeight: '36px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
};

export default config;
