/**
 * Mock trip data for Phase 1 (Experience Prototype).
 *
 * These trips are used to populate the discovery feed before backend
 * integration is complete. Each trip includes mood and taste tags so
 * the feed can simulate personalized filtering based on onboarding answers.
 *
 * Replace with API calls in Phase 3.
 */

import type { Trip } from '@/types/trip';

export const MOCK_TRIPS: Trip[] = [
  {
    id: 'trip-001',
    title: 'The Quiet Dolomites',
    destination: 'Cortina d\'Ampezzo',
    country: 'Italy',
    duration: '7 nights',
    tagline: 'Find stillness above the clouds.',
    mood: ['want-to-slow-down', 'need-a-break', 'need-inspiration'],
    tastes: ['mountains', 'boutique', 'quiet', 'wellness'],
    imageUrl: '/images/discover/quiet-dolomites.jpg',
  },
  {
    id: 'trip-002',
    title: 'Mekong River Drift',
    destination: 'Luang Prabang',
    country: 'Laos',
    duration: '10 nights',
    tagline: 'Let the river decide your pace.',
    mood: ['want-to-slow-down', 'want-to-reconnect', 'escape-routine'],
    tastes: ['forests', 'cultural', 'slow-travel', 'remote'],
    imageUrl: '/images/discover/coral-reef.jpg',
  },
  {
    id: 'trip-003',
    title: 'Patagonia Edge',
    destination: 'Torres del Paine',
    country: 'Chile',
    duration: '12 nights',
    tagline: 'Where the wind rewrites your plans.',
    mood: ['want-adventure', 'want-unexpected', 'need-inspiration'],
    tastes: ['mountains', 'adventure', 'remote', 'quiet'],
    imageUrl: '/images/discover/scottish-highlands.jpg',
  },
  {
    id: 'trip-004',
    title: 'Amalfi Slow Season',
    destination: 'Positano',
    country: 'Italy',
    duration: '6 nights',
    tagline: 'Sun, salt, and no itinerary.',
    mood: ['need-a-break', 'want-to-reconnect', 'escape-routine'],
    tastes: ['beaches', 'luxury', 'vibrant', 'cultural'],
    imageUrl: '/images/discover/palm-beach-aerial.jpg',
  },
  {
    id: 'trip-005',
    title: 'Kyoto in Autumn',
    destination: 'Kyoto',
    country: 'Japan',
    duration: '9 nights',
    tagline: 'A season that teaches you to let go.',
    mood: ['want-to-slow-down', 'need-inspiration', 'want-to-reconnect'],
    tastes: ['cultural', 'wellness', 'quiet', 'boutique'],
    imageUrl: '/images/discover/kyoto-autumn.jpg',
  },
  {
    id: 'trip-006',
    title: 'Scottish Highlands Wild',
    destination: 'Isle of Skye',
    country: 'Scotland',
    duration: '8 nights',
    tagline: 'Untamed, honest, unforgettable.',
    mood: ['want-adventure', 'want-unexpected', 'need-a-break'],
    tastes: ['mountains', 'remote', 'adventure', 'quiet'],
    imageUrl: '/images/discover/scottish-highlands.jpg',
  },
  {
    id: 'trip-007',
    title: 'Lisbon Light',
    destination: 'Lisbon',
    country: 'Portugal',
    duration: '5 nights',
    tagline: 'Golden hour, every hour.',
    mood: ['want-to-reconnect', 'escape-routine', 'need-inspiration'],
    tastes: ['cultural', 'vibrant', 'boutique', 'coastal'],
    imageUrl: '/images/discover/lisbon-light.jpg',
  },
  {
    id: 'trip-008',
    title: 'Namib Desert Silence',
    destination: 'Sossusvlei',
    country: 'Namibia',
    duration: '8 nights',
    tagline: 'Stillness as far as you can see.',
    mood: ['want-to-slow-down', 'want-adventure', 'need-inspiration'],
    tastes: ['remote', 'adventure', 'quiet', 'wellness'],
    imageUrl: '/images/discover/quiet-dolomites.jpg',
  },
  {
    id: 'trip-009',
    title: 'Azores Green Hours',
    destination: 'São Miguel',
    country: 'Portugal',
    duration: '7 nights',
    tagline: 'An island that forgets to rush.',
    mood: ['want-to-slow-down', 'want-to-reconnect', 'need-a-break'],
    tastes: ['coastal', 'mountains', 'slow-travel', 'wellness'],
    imageUrl: '/images/discover/banff-winter.jpg',
  },
  {
    id: 'trip-010',
    title: 'Rajasthan Gold',
    destination: 'Jodhpur',
    country: 'India',
    duration: '9 nights',
    tagline: 'Color, dust, and devotion.',
    mood: ['want-adventure', 'need-inspiration', 'want-unexpected'],
    tastes: ['cultural', 'vibrant', 'boutique', 'adventure'],
    imageUrl: '/images/discover/oaxaca-table.jpg',
  },
  {
    id: 'trip-011',
    title: 'Norwegian Fjord Light',
    destination: 'Lofoten Islands',
    country: 'Norway',
    duration: '8 nights',
    tagline: 'Midnight sun over still water.',
    mood: ['want-to-slow-down', 'want-adventure', 'need-inspiration'],
    tastes: ['mountains', 'remote', 'coastal', 'quiet'],
    imageUrl: '/images/discover/scottish-highlands.jpg',
  },
  {
    id: 'trip-012',
    title: 'Oaxaca Slow Table',
    destination: 'Oaxaca City',
    country: 'Mexico',
    duration: '6 nights',
    tagline: 'Eat, wander, repeat.',
    mood: ['want-to-reconnect', 'escape-routine', 'need-inspiration'],
    tastes: ['cultural', 'vibrant', 'boutique', 'slow-travel'],
    imageUrl: '/images/discover/oaxaca-table.jpg',
  },
  {
    id: 'trip-013',
    title: 'Santorini Off-Season',
    destination: 'Oia',
    country: 'Greece',
    duration: '5 nights',
    tagline: 'The crowds leave, the light stays.',
    mood: ['need-a-break', 'want-to-slow-down', 'want-to-reconnect'],
    tastes: ['coastal', 'luxury', 'quiet', 'boutique'],
    imageUrl: '/images/discover/maldives-shore.jpg',
  },
  {
    id: 'trip-014',
    title: 'Banff Winter Quiet',
    destination: 'Lake Louise',
    country: 'Canada',
    duration: '7 nights',
    tagline: 'Snow finds the noise and erases it.',
    mood: ['want-to-slow-down', 'need-a-break', 'want-adventure'],
    tastes: ['mountains', 'remote', 'wellness', 'quiet'],
    imageUrl: '/images/discover/banff-winter.jpg',
  },
  {
    id: 'trip-015',
    title: 'New Zealand South',
    destination: 'Queenstown',
    country: 'New Zealand',
    duration: '11 nights',
    tagline: 'Every road bends toward a view.',
    mood: ['want-adventure', 'want-unexpected', 'need-inspiration'],
    tastes: ['mountains', 'adventure', 'remote', 'coastal'],
    imageUrl: '/images/discover/quiet-dolomites.jpg',
  },
  {
    id: 'trip-016',
    title: 'Cappadocia at Dawn',
    destination: 'Göreme',
    country: 'Turkey',
    duration: '5 nights',
    tagline: 'Wake before the balloons rise.',
    mood: ['need-inspiration', 'want-unexpected', 'escape-routine'],
    tastes: ['cultural', 'boutique', 'adventure', 'quiet'],
    imageUrl: '/images/discover/kyoto-autumn.jpg',
  },
  {
    id: 'trip-017',
    title: 'Provence Lavender Roads',
    destination: 'Gordes',
    country: 'France',
    duration: '6 nights',
    tagline: 'Slow drives between violet fields.',
    mood: ['want-to-slow-down', 'want-to-reconnect', 'need-a-break'],
    tastes: ['cultural', 'boutique', 'slow-travel', 'coastal'],
    imageUrl: '/images/discover/provence-roads.jpg',
  },
  {
    id: 'trip-018',
    title: 'Maldives Quiet Atoll',
    destination: 'Baa Atoll',
    country: 'Maldives',
    duration: '6 nights',
    tagline: 'Nothing to do but float.',
    mood: ['need-a-break', 'want-to-slow-down', 'want-to-reconnect'],
    tastes: ['beaches', 'luxury', 'wellness', 'quiet'],
    imageUrl: '/images/discover/maldives-shore.jpg',
  },
  {
    id: 'trip-019',
    title: 'Iceland Ring Road',
    destination: 'Vík',
    country: 'Iceland',
    duration: '9 nights',
    tagline: 'Where the road and the wild trade places.',
    mood: ['want-adventure', 'want-unexpected', 'escape-routine'],
    tastes: ['mountains', 'remote', 'adventure', 'coastal'],
    imageUrl: '/images/discover/banff-winter.jpg',
  },
  {
    id: 'trip-020',
    title: 'Vietnam Coast Drift',
    destination: 'Hoi An',
    country: 'Vietnam',
    duration: '8 nights',
    tagline: 'Lanterns, rivers, and slow mornings.',
    mood: ['want-to-slow-down', 'want-to-reconnect', 'need-inspiration'],
    tastes: ['coastal', 'cultural', 'slow-travel', 'vibrant'],
    imageUrl: '/images/discover/palm-beach-aerial.jpg',
  },
];
